### ISSUE TITLE
User authentication failed

### ISSUE THREAD

**Issue by brunojppb** [brunojppb/rails_api#1]
Problems with user authentication. When I try to log_in user with Devise, it raises an error:

```
Failures:

  1) Api::V1::SessionsController POST #create when the credentials are correct returns the user record corresponding to the given credentilas
     Failure/Error: post :create, { session: credentials }
     NoMethodError:
       undefined method `user' for nil:NilClass
     # ./app/controllers/api/v1/sessions_controller.rb:9:in `create'
     # ./spec/controllers/api/v1/sessions_controller_spec.rb:14:in `block (4 levels) in <top (required)>'
```

My Session Controller:

```
class Api::V1::SessionsController < ApplicationController

  def create
    user_password = params[:session][:password]
    user_email = params[:session][:email]
    user = user_email.present? && User.find_by(email: user_email)

    if user.valid_password? user_password
      sign_in user, store: false
      user.generate_authentication_token!
      user.save
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: "Invalid email or password" }, status: 422
    end
  end

end
```

My sessions_controller_spec:

```
require 'rails_helper'

RSpec.describe Api::V1::SessionsController, :type => :controller do

  describe "POST #create" do

    before(:each) do
      @user = FactoryGirl.create :user
    end

    context "when the credentials are correct" do
      before(:each) do
        credentials = { email: @user.email, password: "12345678" }
        post :create, { session: credentials }
      end

      it "returns the user record corresponding to the given credentilas" do
        @user.reload
        expect(json_response[:auth_token]).to eql @user.auth_token
      end

      it { should respond_with 200 }
    end

    context "when the credentials are incorrect" do
      before(:each) do
        credentials = { email: @user.email, password: "invalidPassword" }
        post :create, { session: credentials }
      end

      it "returns a json with an error" do
        expect(json_response[:errors]).to eql "invalid email or password"
      end

      it { should respond_with 422 }
    end

  end

end

```
